[launch]
spp = 1000
maxPathLength = 30

[frame]
width = 800
height = 500
resolution = 1000
#hdr = true
hdr = false
exposure = 1.0
denoise = false

[tile]
width = 64
height = 64

[camera]
# camera faces local -z
position = [1.7, 7.8, 12.2]
# XYZ Euler in degree
rotation = [-28.9, 3.34, 0.0]

[miss]
color = [0.0, 0.0, 0.0]

[[include]]
file = "prism.toml"