[launch]
spp = 1000
maxPathLength = 3

[frame]
width = 800
height = 800
resolution = 1000
hdr = true
exposure = 100

[tile]
width = 64
height = 64

[camera]
# camera faces local -z
position = [0.0, 1.0, 5.0]

[miss]
color = [0.0, 0.0, 0.0]

[[include]]
file = "CornellBox-Original.toml"