[launch]
spp = 100
maxPathLength = 15
params = "g_LaunchParams"

[frame]
width = 800
height = 800
resolution = 1000

[tile]
width = 64
height = 64

[camera]
# camera faces local -z
position = [0.0, 1.0, 5.0]

[[raygen]]
name = "path"
# relative to ptx dir
module = "pipeline.ptx"
entry = "__raygen__entry"

[[miss]]
name = "miss"
module = "pipeline.ptx"
entry = "__miss__entry"

[[exception]]
name = "exception"
module = "pipeline.ptx"
entry = "__exception__entry"

[[hit]]
# all materials will use hit group with name "default"
name = "default"
moduleCH = "pipeline.ptx"
entryCH = "__closesthit__entry"
moduleAH = "pipeline.ptx"
entryAH = "__anyhit__entry"

[[include]]
file = "CornellBox-Original.toml"