[launch]
spp = 100
maxPathLength = 4

[frame]
width = 800
height = 800
resolution = 1000
# hdr = true
hdr = false
exposure = 1
#denoise = true

[tile]
width = 64
height = 64

[camera]
# camera faces local -z
position = [0.0, 1.0, 5.0]

[miss]
color = [0.0, 0.0, 0.0]

[[include]]
file = "CornellBox-Original.toml"